apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: platform-app-alerts
  labels:
    release: monitoring
spec:
  groups:
    - name: platform-app
      rules:
        - alert: PlatformAppDown
          expr: up{namespace="demo", service="platform-app"} == 0
          for: 30s
          labels:
            severity: warning
          annotations:
            summary: Platform application is down