replicaCount: 2

image:
  repository: ghcr.io/harisenthil1/k8s-gitops-platform
  tag: "3c32f9f900e43b78379a35b097d8544c332213bc"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 60

secret:
  appApiKey: "demo-secret-change-me"

networkPolicy:
  enabled: true
